
services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"
    networks:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    environment:
      DB_DSN: postgres://user:password@postgres:5432/db
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    environment:
      VITE_API_URL: http://localhost:8000/api
    ports:
      - "3000:80"
    networks:
      - backend

networks:
  backend:
    driver: bridge
 
